version: '3'

services:
  db:
    image: mysql
    container_name: yehan-admin-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'example'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: 'yehan-admin'
      MYSQL_USER: 'yehan'
      MYSQL_PASSWORD: 'juziman'
    ports:
      - '3307:3306'
    volumes:
      - yehan_admin_mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis
    container_name: yehan-admin-redis
    ports:
      - '6379:6379'
    volumes:
      - yehan_admin_redis:/var/lib/redis
    command: redis-server --appendonly yes --requirepass example
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

volumes:
  yehan_admin_mysql:
  yehan_admin_redis:
